export default [
  {
    id: 1,
    name: "Monstera",
    pic: "../../../public/assets/monstera.jpg",
    price: 15,
    sun: 3,
    water: 2,
    sunkey: "monst-sun",
    waterkey: "monst-wat",
  },
  {
    id: 2,
    name: "Ficus lyrata",
    pic: "./assets/lyrata.jpg",
    price: 22,
    sun: 2,
    water: 1,
    sunkey: "fic-sun",
    waterkey: "fic-wat",
  },
  {
    id: 3,
    name: "Photos Argenté",
    pic: "./assets/photos.jpg",
    price: 9,
    sun: 2,
    water: 1,
    sunkey: "phot-sun",
    waterkey: "phot-wat",
  },
  {
    id: 4,
    name: "Calathea",
    pic: "./assets/calathea.jpg",
    price: 20,
    sun: 3,
    water: 2,
    sunkey: "calat-sun",
    waterkey: "calat-wat",
  },
  {
    id: 5,
    name: "Olivier",
    pic: "./assets/olivier.jpg",
    price: 25,
    sun: 1,
    water: 3,
    sunkey: "oli-sun",
    waterkey: "oli-wat",
  },
  {
    id: 6,
    name: "Cactus",
    pic: "./assets/cactus.jpg",
    price: 6,
    sun: 1,
    water: 2,
    sunkey: "cact-sun",
    waterkey: "cact-wat",
  },
  {
    id: 7,
    name: "Basilic",
    pic: "./assets/basilic.jpg",
    price: 5,
    sun: 3,
    water: 2,
    sunkey: "basil-sun",
    waterkey: "basil-wat",
  },
  {
    id: 8,
    name: "Succulente",
    pic: "./assets/succulente.jpg",
    price: 8,
    sun: 1,
    water: 2,
    sunkey: "succ-sun",
    waterkey: "succ-wat",
  },
  {
    id: 9,
    name: "Menthe",
    pic: "./assets/menthe.jpg",
    price: 4,
    sun: 2,
    water: 2,
    sunkey: "menth-sun",
    waterkey: "menth-wat",
  },
];
